benchmark_dir: ../dataset/benchmarks/generation_gt
results_dir: ../dataset/results/generation_gen/multi_agent
batches_config_path: ../dataset/batches/generation/batches.yaml

variants:
  - image_only
  # - text_level_1
  # - text_level_2
  # - image_text_level_1
  # - image_text_level_2

channels:
  channel_1:
    figma_file_key: JtTP5OvsUBvSiS2g5BK95t
    api_base_url: http://localhost:8000

  channel_2:
    figma_file_key: fKAsAWsx28xTdWlAogIwga
    api_base_url: http://localhost:8001