benchmark_dir: ../dataset/benchmarks/modification_gt/task-1
results_dir: ../dataset/results/modification_gen
modification_task: task-1
batches_config_path:

variants:
  # - without_oracle
  # - perfect_hierachy
  # - perfect_canvas

channels:
  channel_1:
    figma_file_key: 
    api_base_url: http://localhost:8000

  channel_2:
    figma_file_key: JtTP5OvsUBvSiS2g5BK95t
    api_base_url: http://localhost:8001
  
  channel_3:
    figma_file_key: fKAsAWsx28xTdWlAogIwga
    api_base_url: http://localhost:8002

  channel_4:
    figma_file_key: 2VpliZkzPrnQLEE3BpxxKy
    api_base_url: http://localhost:8003

  channel_5:
    figma_file_key: QjNESp2W9mnEpJlARuXXHw
    api_base_url: http://localhost:8004